"""update booking table

Revision ID: 14846bf35be6
Revises: 4440a96680f4
Create Date: 2025-06-16 08:48:18.411185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14846bf35be6'
down_revision = '4440a96680f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('booking_dates', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('booking_dates')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
